In [2]:
import yfinance as yf

In [4]:
msft = yf.Ticker("MSFT")

In [8]:
msft.get_actions()

                           Dividends  Stock Splits
Date
1987-09-21 00:00:00-04:00       0.00           2.0
1990-04-16 00:00:00-04:00       0.00           2.0
1991-06-27 00:00:00-04:00       0.00           1.5
1992-06-15 00:00:00-04:00       0.00           1.5
1994-05-23 00:00:00-04:00       0.00           2.0
...                              ...           ...
2025-05-15 00:00:00-04:00       0.83           0.0
2025-08-21 00:00:00-04:00       0.83           0.0
2025-11-20 00:00:00-05:00       0.91           0.0
2026-02-19 00:00:00-05:00       0.91           0.0
2026-05-21 00:00:00-04:00       0.91           0.0

[99 rows x 2 columns]

In [11]:
yf.download('GLD', start='2020-01-01', end='2020-01-31')

C:\Users\PC\AppData\Local\Temp\ipykernel_11520\273285438.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download('GLD', start='2020-01-01', end='2020-01-31')
c:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\site-packages\yfinance\scrapers\history.py:204: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker             GLD         GLD         GLD         GLD       GLD
Date
2020-01-02  143.949997  144.210007  143.399994  143.860001   7733800
2020-01-03  145.860001  146.320007  145.399994  145.750000  12272800
2020-01-06  147.389999  148.479996  146.949997  148.440002  14403300
2020-01-07  147.970001  148.139999  147.429993  147.570007   7978500
2020-01-08  146.860001  148.610001  146.139999  148.490005  22248500
2020-01-09  146.029999  146.410004  145.440002  146.070007  10292300
2020-01-10  146.910004  146.990005  146.169998  146.220001   6183300
2020-01-13  145.820007  146.380005  145.779999  146.350006   7593800
2020-01-14  145.690002  145.809998  145.080002  145.419998   6589700
2020-01-15  146.539993  146.729996  145.820007  146.210007   6510000
2020-01-16  146.309998  146.470001  145.759995  146.270004   6069100
2020-01-17  146.580002  146.990005  146.309998  146.509995  11121100
2020-01-21  146.740005  146.860001  145.550003  145.770004   6086100
2020-01-22  146.789993  146.809998  146.380005  146.679993   4778200
2020-01-23  147.119995  147.619995  146.619995  147.000000   8419800
2020-01-24  147.979996  148.380005  146.889999  146.899994   9919900
2020-01-27  148.990005  149.320007  148.460007  149.240005   9988100
2020-01-28  147.660004  148.559998  147.529999  148.360001   7543100
2020-01-29  148.460007  148.559998  147.610001  147.699997   5013100
2020-01-30  148.470001  149.309998  148.009995  148.690002   9119500